# Generated by Django 5.0 on 2025-01-03 04:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="story",
            name="content",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="story_covers/"),
        ),
        migrations.AddField(
            model_name="story",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="story",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_stories", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="StoryShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("platform", models.CharField(max_length=50)),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stories.story"
                    ),
                ),
            ],
            options={
                "unique_together": {("story", "shared_by", "platform")},
            },
        ),
        migrations.AddField(
            model_name="story",
            name="shares",
            field=models.ManyToManyField(
                related_name="shared_stories",
                through="stories.StoryShare",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
